from .State import BattleState

class BattleHandler:
	def __init__(self, view_swapped: bool, log_messages: bool): ...

	def log_battle(self, message: str): ...
	def tick(self) -> bool: ...
	def reset(self): ...
	def save_replay(self, path: str) -> bool: ...
	def load_replay(self, path: str): ...
	def save_state(self, path: str) -> bool: ...
	def load_state(self, path: str): ...
	def stop_replay(self): ...

	@property
	def finished(self) -> bool: ...

	@property
	def playing_replay(self) -> bool: ...

	@property
	def state(self) -> BattleState: ...

	def start(self): ...