class DamageResult:
	def __init__(self, critical = False, damage = 0, affect = True, isVeryEffective = False, isNotVeryEffective = False): ...

	@property
	def critical(self): ...
	@critical.setter
	def critical(self, value): ...

	@property
	def damage(self): ...
	@damage.setter
	def damage(self, value): ...

	@property
	def affect(self): ...
	@affect.setter
	def affect(self, value): ...

	@property
	def is_very_effective(self): ...
	@is_very_effective.setter
	def is_very_effective(self, value): ...

	@property
	def is_not_very_effective(self): ...
	@is_not_very_effective.setter
	def is_not_very_effective(self, value): ...