class MoveIndex(int):
	Empty: MoveIndex
	Pound: MoveIndex
	Karate_Chop: MoveIndex
	Doubleslap: MoveIndex
	Comet_Punch: MoveIndex
	Mega_Punch: MoveIndex
	Pay_Day: MoveIndex
	Fire_Punch: MoveIndex
	Ice_Punch: MoveIndex
	Thunder_Punch: MoveIndex
	Scratch: MoveIndex
	Vise_Grip: MoveIndex
	Guillotine: MoveIndex
	Razor_Wind: MoveIndex
	Swords_Dance: MoveIndex
	Cut: MoveIndex
	Gust: MoveIndex
	Wing_Attack: MoveIndex
	Whirlwind: MoveIndex
	Fly: MoveIndex
	Bind: MoveIndex
	Slam: MoveIndex
	Vine_Whip: MoveIndex
	Stomp: MoveIndex
	Double_Kick: MoveIndex
	Mega_Kick: MoveIndex
	Jump_Kick: MoveIndex
	Rolling_Kick: MoveIndex
	Sand_Attack: MoveIndex
	Headbutt: MoveIndex
	Horn_Attack: MoveIndex
	Fury_Attack: MoveIndex
	Horn_Drill: MoveIndex
	Tackle: MoveIndex
	Body_Slam: MoveIndex
	Wrap: MoveIndex
	Take_Down: MoveIndex
	Thrash: MoveIndex
	Double_Edge: MoveIndex
	Tail_Whip: MoveIndex
	Poison_Sting: MoveIndex
	Twineedle: MoveIndex
	Pin_Missile: MoveIndex
	Leer: MoveIndex
	Bite: MoveIndex
	Growl: MoveIndex
	Roar: MoveIndex
	Sing: MoveIndex
	Supersonic: MoveIndex
	Sonic_Boom: MoveIndex
	Disable: MoveIndex
	Acid: MoveIndex
	Ember: MoveIndex
	Flamethrower: MoveIndex
	Mist: MoveIndex
	Water_Gun: MoveIndex
	Hydro_Pump: MoveIndex
	Surf: MoveIndex
	Ice_Beam: MoveIndex
	Blizzard: MoveIndex
	Psybeam: MoveIndex
	Bubblebeam: MoveIndex
	Aurora_Beam: MoveIndex
	Hyper_Beam: MoveIndex
	Peck: MoveIndex
	Drill_Peck: MoveIndex
	Submission: MoveIndex
	Low_Kick: MoveIndex
	Counter: MoveIndex
	Seismic_Toss: MoveIndex
	Strength: MoveIndex
	Absorb: MoveIndex
	Mega_Drain: MoveIndex
	Leech_Seed: MoveIndex
	Growth: MoveIndex
	Razor_Leaf: MoveIndex
	Solarbeam: MoveIndex
	Poisonpowder: MoveIndex
	Stun_Spore: MoveIndex
	Sleep_Powder: MoveIndex
	Petal_Dance: MoveIndex
	String_Shot: MoveIndex
	Dragon_Rage: MoveIndex
	Fire_Spin: MoveIndex
	Thundershock: MoveIndex
	Thunderbolt: MoveIndex
	Thunder_Wave: MoveIndex
	Thunder: MoveIndex
	Rock_Throw: MoveIndex
	Earthquake: MoveIndex
	Fissure: MoveIndex
	Dig: MoveIndex
	Toxic: MoveIndex
	Confusion: MoveIndex
	Psychic_M: MoveIndex
	Hypnosis: MoveIndex
	Meditate: MoveIndex
	Agility: MoveIndex
	Quick_Attack: MoveIndex
	Rage: MoveIndex
	Teleport: MoveIndex
	Night_Shade: MoveIndex
	Mimic: MoveIndex
	Screech: MoveIndex
	Double_Team: MoveIndex
	Recover: MoveIndex
	Harden: MoveIndex
	Minimize: MoveIndex
	Smokescreen: MoveIndex
	Confuse_Ray: MoveIndex
	Withdraw: MoveIndex
	Defense_Curl: MoveIndex
	Barrier: MoveIndex
	Light_Screen: MoveIndex
	Haze: MoveIndex
	Reflect: MoveIndex
	Focus_Energy: MoveIndex
	Bide: MoveIndex
	Metronome: MoveIndex
	Mirror_Move: MoveIndex
	Self_Destruct: MoveIndex
	Egg_Bomb: MoveIndex
	Lick: MoveIndex
	Smog: MoveIndex
	Sludge: MoveIndex
	Bone_Club: MoveIndex
	Fire_Blast: MoveIndex
	Waterfall: MoveIndex
	Clamp: MoveIndex
	Swift: MoveIndex
	Skull_Bash: MoveIndex
	Spike_Cannon: MoveIndex
	Constrict: MoveIndex
	Amnesia: MoveIndex
	Kinesis: MoveIndex
	Softboiled: MoveIndex
	Hi_Jump_Kick: MoveIndex
	Glare: MoveIndex
	Dream_Eater: MoveIndex
	Poison_Gas: MoveIndex
	Barrage: MoveIndex
	Leech_Life: MoveIndex
	Lovely_Kiss: MoveIndex
	Sky_Attack: MoveIndex
	Transform: MoveIndex
	Bubble: MoveIndex
	Dizzy_Punch: MoveIndex
	Spore: MoveIndex
	Flash: MoveIndex
	Psywave: MoveIndex
	Splash: MoveIndex
	Acid_Armor: MoveIndex
	Crabhammer: MoveIndex
	Explosion: MoveIndex
	Fury_Swipes: MoveIndex
	Bonemerang: MoveIndex
	Rest: MoveIndex
	Rock_Slide: MoveIndex
	Hyper_Fang: MoveIndex
	Sharpen: MoveIndex
	Conversion: MoveIndex
	Tri_Attack: MoveIndex
	Super_Fang: MoveIndex
	Slash: MoveIndex
	Substitute: MoveIndex
	Struggle: MoveIndex
