from .State import BattleState

class Gen1Renderer :
	def __init__(self, variant: str | bytes, has_colors: bool): ...

	def update(self): ...
	def reset(self): ...
	def consume_event(self, event: dict): ...

	def previous_turn(self): ...
	def next_turn(self): ...
	def render_pic(self) -> bytes: ...

	@property
	def size(self) -> tuple[int, int]: ...

	@property
	def turn(self) -> int: ...
	@turn.setter
	def turn(self, t: int): ...

	@property
	def animation_ended(self) -> bool: ...

	@property
	def sound_disabled(self) -> bool: ...
	@sound_disabled.setter
	def sound_disabled(self, v: bool): ...

	@property
	def display_turn(self) -> bool: ...
	@display_turn.setter
	def display_turn(self, v: bool): ...

	@property
	def music_disabled(self) -> bool: ...
	@music_disabled.setter
	def music_disabled(self, v: bool): ...

	@property
	def waiting(self) -> bool: ...
	@waiting.setter
	def waiting(self, v: bool): ...

	@property
	def state(self): ...
	@state.setter
	def state(self, v: BattleState): ...