list_int = list[int]

class RandomGenerator:
	def __init__(self, alloc=True): ...
	def __call__(self) -> int: ...
	def generate_list(self, size: int): ...
	def reset(self): ...

	@property
	def list(self) -> list_int: ...
	@list.setter
	def list(self, rlist: list_int): ...

	@property
	def index(self) -> int: ...
	@index.setter
	def index(self, index: int): ...
