# distutils: language = c++

from ._StatusChange cimport StatusChange as __StatusChange, statusToString, statusToStringShort, STATUS_NONE, STATUS_ASLEEP_FOR_1_TURN, STATUS_ASLEEP_FOR_2_TURN, STATUS_ASLEEP_FOR_3_TURN, STATUS_ASLEEP_FOR_4_TURN, STATUS_ASLEEP_FOR_5_TURN, STATUS_ASLEEP_FOR_6_TURN, STATUS_ASLEEP_FOR_7_TURN, STATUS_ASLEEP, STATUS_POISONED, STATUS_BURNED, STATUS_FROZEN, STATUS_PARALYZED, STATUS_KO, STATUS_BADLY_POISONED, STATUS_ANY_NON_VOLATILE_STATUS, STATUS_LEECHED, STATUS_CONFUSED_FOR_1_TURN, STATUS_CONFUSED_FOR_2_TURN, STATUS_CONFUSED_FOR_3_TURN, STATUS_CONFUSED_FOR_4_TURN, STATUS_CONFUSED, STATUS_FLINCHED

cpdef enum StatusChange:
	OK = STATUS_NONE
	Asleep_for_1_turn = STATUS_ASLEEP_FOR_1_TURN
	Asleep_for_2_turn = STATUS_ASLEEP_FOR_2_TURN
	Asleep_for_3_turn = STATUS_ASLEEP_FOR_3_TURN
	Asleep_for_4_turn = STATUS_ASLEEP_FOR_4_TURN
	Asleep_for_5_turn = STATUS_ASLEEP_FOR_5_TURN
	Asleep_for_6_turn = STATUS_ASLEEP_FOR_6_TURN
	Asleep_for_7_turn = STATUS_ASLEEP_FOR_7_TURN
	Asleep = STATUS_ASLEEP
	Poisoned = STATUS_POISONED
	Burned = STATUS_BURNED
	Frozen = STATUS_FROZEN
	Paralyzed = STATUS_PARALYZED
	KO = STATUS_KO
	Badly_poisoned = STATUS_BADLY_POISONED
	Any_non_volatile_status = STATUS_ANY_NON_VOLATILE_STATUS
	Leeched = STATUS_LEECHED
	Confused_for_1_turn = STATUS_CONFUSED_FOR_1_TURN
	Confused_for_2_turn = STATUS_CONFUSED_FOR_2_TURN
	Confused_for_3_turn = STATUS_CONFUSED_FOR_3_TURN
	Confused_for_4_turn = STATUS_CONFUSED_FOR_4_TURN
	Confused = STATUS_CONFUSED
	Flinched = STATUS_FLINCHED

def status_to_string(s):
	return statusToString(s).decode('ASCII')

def status_to_string_short(s):
	return statusToStringShort(s).decode('ASCII')
