from .State import BattleState
from .Pokemon import Pokemon

def load_trainer(data: bytes, state: BattleState) -> tuple[str, list[Pokemon]]: ...
def save_trainer(trainer: tuple[str, list[Pokemon]]) -> bytes: ...
